### ISSUE TITLE
Proto: Improve Pagination Fields

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#1014]
https://github.com/clouditor/clouditor/blob/995e9390d73a635014fe8861c6f570a7dec640c7/api/orchestrator/orchestrator.proto#L455-L458

2 suggestions:
1. We could pack them into one `pagination_options` message, move it to a central .proto file and use it everywhere needed (it is needed multiple times)
2. Add validation rules. E.g.  `page_size` >= 0

**Comment by oxisto** [comment]
The problem I see with packing them into a message is that you cannot directly embed them anymore and that you always need to use them like `?pagination_options.pageSize=900` in a REST query. That is very cumbersome in my opinion. 

Unfortunately, I have not seen anything that allows for a direct embedding of a message on the "same level" as the message properties itself.

**Comment by lebogg** [comment]
Yes, unfortunately there is no and won't be a such feature in  protobuf: https://github.com/protocolbuffers/protobuf/issues/5372#issuecomment-448719152

Maybe in buf generator? But I don't think so.

**Comment by oxisto** [comment]
> Yes, unfortunately there is no and won't be a such feature in protobuf: [protocolbuffers/protobuf#5372 (comment)](https://github.com/protocolbuffers/protobuf/issues/5372#issuecomment-448719152)
> 
> Maybe in buf generator? But I don't think so.

Doesn't look like it. I think for filters (see the other PRs) its ok, but for these I fear we need to copy/pase them into the individual requests (at least for now).
