### ISSUE TITLE
Proto: Improve Filter Fields 

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#1015]
In several API calls, we have single filtering fields which are sometimes prefixed with `filtered_` , sometimes with `filter_` and sometimes not prefixed at all.

# Suggestion
Pack them like in #999 : 
```
message Filter {
  string cloud_service_id = 1;
  string tool_id = 2;
}
```

**Comment by luis-gasparschroeder** [comment]
Different filter annotations in:
- discovery.proto
- evidence_store.proto
- orchestrator.proto
