### ISSUE TITLE
Don't use the same Filter for multiple messages (proto)

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#1053]
https://github.com/clouditor/clouditor/blob/cf4cfd99102be5aa7c497706c2bd9d8d54daa73c/api/orchestrator/orchestrator.proto#L468-L477

Here, the `Filter` is used for both `ListAssessmentResultsRequest` and `ListAssessmentToolsRequest`. I guess the fields are not appropriate for both cases? In addition, the comments refer only to assessment results.

**Comment by oxisto** [comment]
Ah, it seems all the filter of the service were merged into a single one. Looks like we need distinct filter objects and then the question is: Is that worth it? Or would it be better just to have a common handling of the filter fields in the service implementation?

**Comment by oxisto** [comment]
We could also embed the filter type directly into the message like this:

```proto
message ListResourcesRequest {
  message Filter {
    optional string type = 1;
    optional string cloud_service_id = 2;
  }

  optional Filter filter = 1;

  int32 page_size = 10;
  string page_token = 11;
  string order_by = 12;
  bool asc = 13;
}
```

**Comment by lebogg** [comment]
> Ah, it seems all the filter of the service were merged into a single one. Looks like we need distinct filter objects and then the question is: Is that worth it? Or would it be better just to have a common handling of the filter fields in the service implementation?

Tricky question. I kinda dislike one filter for multiple requests. But, on the other side, if we have one such big filter and comment appropriately to which Requests they belong and also do the handling of these filters in the implementation (like you mentioned), it could work.

Otherwise, I would prefer the embedded option in the case of single filters.

**Comment by oxisto** [comment]
We need to check, if the "new" approach (unique filter message in request) is used everywhere.
