### ISSUE TITLE
Add authorization to certificate endpoints

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#1056]
**Is your feature request related to a problem? Please describe.**
In the certification endpoints, we don't take into account if the user is authorized.

**Describe the solution you'd like**
Add authorization to all endpoints regarding certification, e.g.  `ListCertificates` and  `GetCertificate`

Should be very straightforward like in the other List requests that got updated previously.

**Comment by luis-gasparschroeder** [comment]
> **Is your feature request related to a problem? Please describe.** Currently, we don't list the certificates based on the user's authorization.
> 
> **Describe the solution you'd like** Add authorization to
> 
> https://github.com/clouditor/clouditor/blob/cf4cfd99102be5aa7c497706c2bd9d8d54daa73c/service/orchestrator/orchestrator.go#L245-L246
> 
> Should be very straightforward like in the other List requests that got updated previously.

It's not related but I'll fix the issue!
