### ISSUE TITLE
Consider removing unused variables/constants in testdata

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#1097]
I'm not sure if they are hold for future implementation or just have been forgotten.
See, e.g., `MockControls`  (and then `MockControl3`, `MockControl4`, `MockControl5` as well) 
https://github.com/clouditor/clouditor/blob/aa233849bd5c7777d61d83fc1f2ff70ac2021bcb/internal/testutil/servicetest/orchestratortest/orchestrator.go#L376
and `MockControlsInScopeSubControl4`

**Comment by anatheka** [comment]
The variables/constants in testdata all appear to be used.
