### ISSUE TITLE
Move (API) error variable to API

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#1098]
Imo, it fits better in the `/api/errors.go`. What do you think? The file already imports the API package, so circular dependencies shouldn't be the evil here.
https://github.com/clouditor/clouditor/blob/aa233849bd5c7777d61d83fc1f2ff70ac2021bcb/service/authorization.go#L49-L50

**Comment by anatheka** [comment]
Maybe we should move all errors to the api folders?

**Comment by oxisto** [comment]
Duplicate of #1045
