### ISSUE TITLE
Add Filter to `ListXXX` requests for logical separation of deployed resources

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#1123]
**Is your feature request related to a problem? Please describe.**
In #1008 we added the possibility to let the engine search only for resources in a specific resource group. While this is fine in some contexts, there are two limitations:
1. A CSP may have a different approach for logically separate environments like PROD, DEV and TEST, e.g. via tagging or simple naming (e.g., PROD_VM1)
2. A CSP may want to do it dynamically while using the Clouditor (UI), i.e. at runtime. With the current approach you need to run a new engine instance and set the environment variable new for switching from, e.g., PROD to DEV. This is not user friendly.

**Describe the solution you'd like**
Add filtering for resource group, tagging and naming in all corresponding `ListXXX` requests

**Describe alternatives you've considered**
I don't have thought of an alternative but maybe there is a better solution?

**Comment by oxisto** [comment]
Shouldn't logically separated resources be separated into two cloud services?

**Comment by oxisto** [comment]
One possible approach could be to have different discoverers with different tool ids and then filter by tool id. For this we need to:
- Store the tool ID in the resource object
- Make tool ID configurable in discoverer
