### ISSUE TITLE
UpdateMetricImplementation does not work properly

### ISSUE THREAD

**Issue by anatheka** [clouditor/clouditor#1140]
**Describe the bug**
UpdateMetricImplementation does not update the metric_implementation if it does not already exist, but the associated metric exists. 

**To Reproduce**
Update a metric_implementation that does not yet exist, e.g. in Medina TEST or DEV. 
`curl -d '{"code":"New test implementation","lang":"LANGUAGE_REGO","metricId":"AccessRightManagementQ1"}'  -H "Authorization: Bearer $TOKEN" -XPUT  https://$DEST/v1/orchestrator/metrics/AccessRightManagementQ1/implementation` 

Error: 
`{
   "code" : 2,
   "details" : [],
   "message" : "could not save metric implementation: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification (SQLSTATE 42P10)"
}`

**Expected behavior**
UpdateMetricImplementation() should also update a metric_implementation if these does not yet exist.

**Additional context**

**Comment by lebogg** [comment]
Technically, this is the right behavior. See also the comment in the API:
```
// Updates an existing metric implementation
  rpc UpdateMetricImplementation(UpdateMetricImplementationRequest)
```

What we need is the `CreateMetricImplementation` endpoint I guess.

**Comment by anatheka** [comment]
Already done.
