### ISSUE TITLE
Discovery: Harmonize property algorithm in httpEndpoint.transportEncryption

### ISSUE THREAD

**Issue by anatheka** [clouditor/clouditor#1261]
We should harmonize the property 'algorithm' in httpEndpoint.transportEncryption. Sometimes it is TLS and sometimes AES 256.

**Comment by oxisto** [comment]
Transport encryption should never be just „aes256“. That sounds like storage encryption

**Comment by oxisto** [comment]
We should probably rename this to something like cipher suites and store the TLS cipher suites if we find any information about them

**Comment by anatheka** [comment]
I added a comment to the transportEncryption in WebProtege.

**Comment by oxisto** [comment]
We split this up into different properties in the Ontology, which need to update here. Will be fixed when we auto-generate the ontology property.
