### ISSUE TITLE
Consider `client factory` of Azure SDK

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#1267]
We currently set up each client individually:
https://github.com/clouditor/clouditor/blob/b02fcd26e6fbf18b5bfb9b667b3f36304bd15233/service/discovery/azure/azure.go#L138-L142

There is also a `client factory`  in the SDK which we may can leverage:
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage#readme-client-factory

**Comment by oxisto** [comment]
It seems that this is not really usable for our purpose, since the factory creates a new client on each request, which would result in a lot of clients in each discovery step.
