### ISSUE TITLE
Change default value of checkbox "not monitored" in Compliance View

### ISSUE THREAD

**Issue by garuppel** [clouditor/clouditor#25]
Currently, the  "BSI C5" and "CIS Microsoft Azure Foundations Benchmark" Views show all Controls. For a better visibility it would be nice if after clicking the "Failed Controls" button the "not monitored" checkbox is not activated by default. 

By clicking the "BSI C5" and "CIS Microsoft Azure Foundations Benchmark" Links I would prefer the activation of the "not monitored" checkbox by default.

**Comment by oxisto** [comment]
Closed by #36
