### ISSUE TITLE
Error in S3 / Bucket Rule "Enable Default Encryption in Buckets"

### ISSUE THREAD

**Issue by garuppel** [clouditor/clouditor#26]
Currently, all S3-Buckets in the View "Rules" are marked as compliant (encrypted) although some buckets are not encrypted.

**Comment by oxisto** [comment]
Nice catch, this is actually a major logic flaw in the current rule engine. Consider the following condition of the rule:

```
Bucket has
    not empty applyServerSideEncryptionByDefault.sseAlgorithmAsString
  in all
    bucketEncryption.rules
```

The problem is/was that the `NotExpression` was actually applied to the result of the `in all` construct and not to the `empty` expression with-in the loop.

**Comment by oxisto** [comment]
I'm trying to fix this by introducing parenthesis in CCL to clarify ambiguous statements, like this:

```
Bucket has
    (not empty applyServerSideEncryptionByDefault.sseAlgorithmAsString)
  in all
    bucketEncryption.rules
```
