### ISSUE TITLE
Distinguish between the different storage account types

### ISSUE THREAD

**Issue by garuppel** [clouditor/clouditor#285]
The Azure discovery should distinguish between the different storage account types, e.g., 
- "Microsoft.Storage/storageAccounts"
- "Microsoft.Storage/storageAccounts/blobServices"
- "Microsoft.Storage/storageAccounts/fileServices"
- "Microsoft.Storage/storageAccounts/blobServices/containers"
- ...

**Comment by oxisto** [comment]
Fixed by #330
