### ISSUE TITLE
Implement `AssignmentRequest` in Orchestrator

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#385]
According to our discovery service / orchestrator flow, we need a new RPC call that the orchestrator offers called `AssignmentRequest`. It should contain:
- Collector ID
- Use gRPC or REST

The answer should be an `Assignment` and should contain:

- Target Cloud Service ID
- URL of Assessment Tool
- URL of Evidence Store

**Comment by anatheka** [comment]
@oxisto do we need this anymore?
