### ISSUE TITLE
Assessment results need to be stored in the orchestrator

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#407]
Using either `StoreAssessmentResult` or  `StoreAssessmentResults`.

**Comment by lebogg** [comment]
I think it is done in #410 , @garuppel ?

**Comment by garuppel** [comment]
Not yet, but I can fix that in the PR #410.

**Comment by lebogg** [comment]
I see `Results map[string]*assessment.Result` and the methods `StoreAssessmentResult(s)` in `orchestrator.go` in #410. I think this is fine for now and I will add the workflow then in the next PR when adapting the workflow to MEDINA.

**Comment by garuppel** [comment]
I re-opened the issue for the migration in PR #419.
