### ISSUE TITLE
CLI: Listing assessment results does not contain `compliant` field

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#414]
**Describe the bug**
When using the CLI command to list assessment results, all fields but `compliant` will be printed.

**To Reproduce**
1. Prep:
   -  `go generate ./...`
   - `go install cmd/cli/cl.go`
2. Run engine: `clouditor.io/clouditor/cmd/engine --db-in-memory`
3. Start discovery (and thus, assessment as well): `cl discovery start`
4. List assessment results: `cl assessment list`

**Output snippet**
 ```
{
      "id":  "b3e65116-064e-433b-b1ad-e20dbde36f92",
      "timestamp":  "2021-12-15T10:07:35.002764902Z",
      "metricId":  "BootLoggingOutput",
      "metricData":  {},
      "evidenceId":  "XXX",
      "resourceId":  "XXX",
      "nonComplianceComments":  "No comments so far"
 }
```

**Expected behavior**
`compliant` field should be also included:
<pre>
{
      "id":  "b3e65116-064e-433b-b1ad-e20dbde36f92",
      "timestamp":  "2021-12-15T10:07:35.002764902Z",
      "metricId":  "BootLoggingOutput",
      "metricData":  {},
      <b>"compliant":  true/false,</b>
      "evidenceId":  "XXX",
      "resourceId":  "XXX",
      "nonComplianceComments":  "No comments so far"
 }
</pre>

**Comment by lebogg** [comment]
@oxisto any idea? I looked into the code: The CLI correctly calls `client.ListAssessmentResults` and the return type is `ListAssessmentResultsResponse` which contains `AssessmentResutls` which contains the `compliant` field.

**Comment by oxisto** [comment]
> @oxisto any idea? I looked into the code: The CLI correctly calls `client.ListAssessmentResults` and the return type is `ListAssessmentResultsResponse` which contains `AssessmentResutls` which contains the `compliant` field.

I see the compliant field, but only if it is not `false`:

```
    {
      "id": "bb735b6e-14a4-40d8-a19b-09d342b353ca",
      "timestamp": "2021-12-15T17:40:19.661107Z",
      "metricId": "TransportEncryptionEnabled",
      "metricData": {},
      "compliant": true,
      "evidenceId": "1652ea8b-c8d3-4ed9-bacd-43452dbe1498",
      "resourceId": "XXXX",
      "nonComplianceComments": "No comments so far"
    },
```

**Comment by oxisto** [comment]
You can set `EmitUnpopulated` to `true` (see https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson#MarshalOptions) in `Session.HandleResponse`

**Comment by lebogg** [comment]
Yes, that is the solution! I will do a mini PR when #410 is committed
