### ISSUE TITLE
Validate or set assessment ID in Orchestrator

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#463]
**Describe the bug**
In the RPC `StoreAssessmentResult` in the orchestrator, we [validate the assessment result (Line 202)](https://github.com/clouditor/clouditor/blob/e481a8b99d1584531f5919554377a1e3ddea27ab/service/orchestrator/orchestrator.go#L202) and then [store it into the map with its ID(L213)](https://github.com/clouditor/clouditor/blob/e481a8b99d1584531f5919554377a1e3ddea27ab/service/orchestrator/orchestrator.go#L213).
But the function `validate` doesn't check the ID. I.e., an assessment result with empty ID is stored with empty key "" and will be overwritten by future assessment results with empy IDs.

**Expected behavior**
Either `validate` checks if ID is set (meaning that results with empty IDs are rejected) or the Orchestrator creates one itself (e.g. UUID) for assessment with no IDs.

**Comment by oxisto** [comment]
As discussed, the assessment tool should set a UUID and the orchestrator should validate this.

**Comment by lebogg** [comment]
Yes, will be addressed in the next PR.
