### ISSUE TITLE
MEDINA Integration

### ISSUE THREAD

**Issue by anatheka** [clouditor/clouditor#466]
- [x] #478
- [x] #481
- [ ] Policy folder path not accessible: How can we import the policy folder to get the metrics? Currently they need to be copied to the repo because of path problems. Or do we ignore that until we retrieve the metrics directly from the metrics catalog?
- [x] #479
- [ ] Implement the tool configuration
- [x] #495

**Comment by oxisto** [comment]
Initial integration is done.
