### ISSUE TITLE
Separate database access from service packages using an interface

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#467]
**Is your feature request related to a problem? Please describe.**

Currently, we are directly using the `gorm` structs in our service packages. This creates problems for external users that might depend on another solution for persistence or just would like to have the choice.

**Describe the solution you'd like**

We already have a `persistence` package, we should introduce some more interfaces to interact with the services packages and then have sub packages, e.g. for gore.

**Comment by lebogg** [comment]
We could also start with using the in-memory DB for our services consequently instead of using maps for storing, e.g., assessment results and evidences.
