### ISSUE TITLE
Addressing left over issues from JWT/JWK code review

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#488]
I accidentally merged #483 too soon, without potentially addressing some of the comments from @garuppel and @lebogg. This issue will provide an overview of things we still want to fix in a separate PR

- [ ] Add comment to `ListPublicKeys` why it returns  a list of a single ("hard-coded") key
- [ ] Check, if we can derive the appropriate signing method based on the key in `issueToken` of the auth server
- [ ] Move auth-related stuff from `service` into `service/middleware`
- [ ] Add godoc compliant comments in `pem.go`
- [ ] Explain why MarshalECPrivateKeyWithPassword and ParseECPrivateKeyFromPEMWithPassword returns an error directly
- [ ] Remove useless `[]byte' cast in ParseECPrivateKeyFromPEMWithPassword
- [ ] Remove useless `string` cast in `CreateDefaultUser`
- [ ] Correct comments in `service/discovery/discovery.go` and remove `ErrNoAuthorizerConfigured`
- [ ] Correct comments in `service/assessment/assessment `
- [ ] Make `DefaultAPIHTTPPort` const
- [ ] Handle deferred error in `service/auth/auth.go`
- [x] #499

**Comment by lebogg** [comment]
Starting the engine and running the discovery via "cl service discovery start" results in
`INFO[0002] gRPC call  clouditor.Discovery  |  Start  |  Unauthenticated   component=grpc error="rpc error: code = Unauthenticated desc = invalid auth token" grpc.code=Unauthenticated grpc.method=Start grpc.service=clouditor.Discovery`
