### ISSUE TITLE
HandleEvidence: Make logging message more human-readable

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#535]
**Describe the bug**
Currently, the log message of [handleEvidence](https://github.com/clouditor/clouditor/blob/f3f4517ac3740742d643b7960e354ef71744d6c9/service/assessment/assessment.go#L225) is, e.g.:
`INFO[0010] Evaluating evidence 1 (1) collected by 1 at seconds:1645574399 nanos:999999999 `

**To Reproduce**
Run engine and assess an evidence.

**Expected behavior**
A human readable message, e.g.:
`INFO[0010] Evaluating evidence with ID: 1 (Resource ID: 1) collected by Tool 1 at 2022-02-22 23:59:59.999999999` or
`INFO[0010] Evaluating evidence (Evidence ID: 1 | Resource ID: 1 | Tool ID: 1 | Time: 2022-02-22 23:59:59.999999999)`

**Additional context**
Use `Timestamp.AsTime()` of the `timestamppb` package

**Comment by anatheka** [comment]
Already fixed in the past.
