### ISSUE TITLE
Azure Discovery: Error getting K8S ingresses

### ISSUE THREAD

**Issue by anatheka** [clouditor/clouditor#552]
ERRO[0006] Could not retrieve resources from discoverer 'Kubernetes Network': could not list ingresses: the server could not find the requested resource  component=discovery

**Comment by garuppel** [comment]
I think the problem are the API versions [1]. I think we have to change the API versions in the yaml files from `v1beta1` to `v1`. 


[1]https://kubernetes.io/docs/reference/using-api/deprecation-guide/

**Comment by anatheka** [comment]
This was closed by MR #664
