### ISSUE TITLE
Add Azure authentication via environment variables

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#555]
**Is your feature request related to a problem? Please describe.**
I tried to use the credentials for an Azure testbed from a MEDINA partner. For that purpose we got the Application (Client) ID, the Tenant ID, Subscription ID, and the Client Secret.
1) I created a credential file including all these items. I set the `AZURE_AUTH_LOCATION` to link to this file - as required by the `NewAuthorizerFromFile` method of the azure package `autorest`. I didn't find any good example how to set it up but I after a lil bit of trial and error, I think it needs to be a JSON. But other than that, I always got some "Credentials\secret are\is missing" error or similar. Maybe some naming issues of the items in the credentials file.
2) Then I come across the `azidentity` package which seems to be the choice in the future according to https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authorization: "Moving forward, authentication for the Azure SDK for Go will be done using the [Azure Identity](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity) package". The `Azure CLI` prompting a warn message when trying to create a credentials file like above with `--sdk-auth` option, supports this case.
I tried to replace the auto rest package in the case of the `ARMTemplate` discovery but had no success. I only got empty resource groups and therefore empty templates. Maybe we can address it in a separate issue. A nice feature of `azidenity` is that it has a `NewDefaultAzureCredential` method which includes a authentication chain which it goes through until it has one that works.
3) The quickest fix is to add to our "chain" of authentication (currently from file and over CLI) the option to authenticate via environment variables. I would prefer this way because even with credential file we have to set the path environment variable. Thus, we can also just simply add the client credentials via environment variables which can also be easily added to our K8s cluster? In addition, using credential files seems not to be the way of choice since it is no option in the preferred `azidentity` package and also the CLI prompts a warning when creating such files.

**Describe the solution you'd like**
Option 3) Add option to authenticate from environment.

**Describe alternatives you've considered**
See 1) and 2)

**Comment by oxisto** [comment]
For future reference, the file needs to look like this:

```json
{
    "clientId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "clientSecret": "secret",
    "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "resourceManagerEndpointUrl": "https://management.azure.com/"
}
```

The important part is that `resourceManagerEndpointUrl` needs to be specified, otherwise this obscure error is thrown.
