### ISSUE TITLE
Concretize error message in assessment component

### ISSUE THREAD

**Issue by anatheka** [clouditor/clouditor#564]
The following error comes, if the resource type is not specified: 
ERRO[3136] Could not evaluate evidence: got type '[]interface {}' but wanted '[]interface {}'. Check if resource types are specified   component=assessment

The part "got type '[]interface {}' but wanted '[]interface {}" is not helpful.

**Comment by lebogg** [comment]
But converting the map to a struct would mean to first convert it to a struct, check its values and then use the map anyway. Since rego only accepts a map. Not sure if that would be of advantage.

**Comment by garuppel** [comment]
> What was the input resulting in that error message? The problem is that we only have a map and no struct. And the values of that map are checked via type assertions.
> 
> But what we maybe can do is to use `"github.com/mitchellh/mapstructure"` to convert the map to an evidence struct and then check the fields. Maybe this is more elegant. Oxisto did this with `Result` in the `policies.go` file as well.

I am not sure, but the problem was, that the resource type was missing. For example as follows and that was missing `		"type":["VirtualMachine","Compute","Resource"]`: 
```
"resource":{
		"blockStorage":null,
		"bootLogging":null,
		"creationTime":0,
		"geoLocation":{
			"region":"eu"
		},
		"id":"ID-test",
		"labels":null,
		"name":"Name-test",
		"networkInterface":null,
		"oSLogging":null,
	}
```
