### ISSUE TITLE
Check if evidence and assessmentResult is nil

### ISSUE THREAD

**Issue by anatheka** [clouditor/clouditor#621]
If an empty evidence is sent to the asssessment component the following error occurs: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbf9f42]
```

**Comment by lebogg** [comment]
I wouldn't close it since it is a possibility that an empty request is sent (nil value since it is a pointer). I will address it in #566

**Comment by garuppel** [comment]
But the validate() function checks that case, or not?

**Comment by anatheka** [comment]
We can close this issue, the current validation function checks this.
