### ISSUE TITLE
Azure Discovery: BootLogging.enabled is always set to false

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#624]
**Describe the bug**
When running Clouditor and looking at the evidences, all VM instances have bootLogging set to false which isn't right.

**To Reproduce**
- Run clouditor
- list evidences
- Compare bootLogging of VMs with settings in the Azure Portal (BootDiagnostic in Azure).

**Expected behavior**
Set bootLogging to true when it is activated (which is "Enable with managed storage account (recommended)" by default)

**Comment by garuppel** [comment]
I think the BootDiagnostics information we do not get from the NewVirtualMachinesClient.ListAllComplete(). I think we have to use the NewVirtualMachinesClient.Get() method.

**Comment by oxisto** [comment]
Is it possible to adjust it using query parameters? I remember that some calls have options to enable additional fields in the list methods.

**Comment by garuppel** [comment]
Maybe, but I have to use the Get method for other configurations anyway. I just need to rewrite the code a bit, then it should hopefully fit. But I will still have another look at the query, maybe it is the better way. Thanks!
