### ISSUE TITLE
Discovery: Clouditor panics after starting discovery

### ISSUE THREAD

**Issue by garuppel** [clouditor/clouditor#626]
**Describe the bug**
Panic occurs some time after the Clouditor's discovery is started.

**To Reproduce**
1. Start Clouditor
2. 'cl service discovery start'
3. Wait or do 2 times 'cl service discovery query'

**Expected behavior**
No panics.

**Additional context**
I think the error happens because of missing mutexes.

**Comment by lebogg** [comment]
Just for the record (we already discussed it internally): For me, no panic occurs.
