### ISSUE TITLE
gRPC `list` functions: Take into account max message length of received messages

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#635]
**Describe the bug**
When generating so many assessment results (AR) that the list of a ARs in `ListAssessementResults()` is bigger than 4MB (4194304 Bytes), gRPC will throw an error. This error, of course, concerns all list calls.

**To Reproduce**
Collect/Generate a lot of evidences/ARs.

**Expected behavior**
Always return lists that are not exceeding 4MB in size. Either cut older ones or implement a mechanism to retrieve multiple lists.

**Additional context**
We could also increase the threshold for maximum message length but that would only delay the problem.

**Comment by oxisto** [comment]
So basically we would need some kind of pagination support for the ListXXX functions, correct?

**Comment by lebogg** [comment]
Yes :+1:

**Comment by lebogg** [comment]
https://cloud.google.com/apis/design/design_patterns#list_pagination
