### ISSUE TITLE
EvidenceStore (API): Remove `response_body` option in `StoreEvidence`

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#636]
**Describe the bug**
Currently, `response_body` is set to "status", indicating that the boolean field "status" of `StoreEvidenceResponse` is used. Actually it is used when doing HTTP requests but the generated OpenAPI Spec tells otherwise: Here the response is the entire `StoreEvidenceResponse` message.

**Expected behavior**
Since we omit the EXPLICIT response body in similar cases, e.g. in StoreAssessmentResult, we should omit here as well. It will implicitly use the entire `StoreEvidenceResponse` then.

**Comment by oxisto** [comment]
Was this fixed in the mean-time?

**Comment by oxisto** [comment]
Yes, was fixed.
