### ISSUE TITLE
Implement metric endpoints 

### ISSUE THREAD

**Issue by garuppel** [clouditor/clouditor#641]
- [ ] UpdateMetricConfiguration()
- [ ] GetMetricImplementation()
- [ ] UpdateMetricImplementation()

**Comment by oxisto** [comment]
Duplicate of https://github.com/clouditor/clouditor/issues/495?

**Comment by garuppel** [comment]
Yes, sorry.

**Comment by garuppel** [comment]
Duplicate of #495
