### ISSUE TITLE
Discovery: Field `serviceId` in evidences not filled

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#658]
**Describe the bug**
We do not insert any information about the service id in discovered evidences. What exactly is the service id anyway? Is it the CSP (Azure, AWS) or a specific service of that CSP (S3, EC2, blob storage) or ...?

**Comment by oxisto** [comment]
The service ID is the ID of the target cloud service, see https://github.com/clouditor/clouditor/blob/01f153aa5ec7f5bc778f0172f0d0ab27e3470dcb/api/orchestrator/orchestrator.proto#L373

**Comment by lebogg** [comment]
Ok thank you. E.g., EC2 right?

**Comment by oxisto** [comment]
> Ok thank you. E.g., EC2 right?

 No. The cloud service of the user which can be comprised of different cloud resources from different loud providers. Per default, a default cloud service is created at startup.
