### ISSUE TITLE
Add checks and rules Azure Storage Accounts required by CIS benchmark

### ISSUE THREAD

**Issue by immqu** [clouditor/clouditor#66]
The Azure CIS benchmark requires 
- access to storage accounts to be restricted (3.7) which can be checked with the property _isAccessAllowedFromAllNetworks_ and 

- access to storage accounts to be enabled for Microsoft services (3.8) which can be checked with the property _canAccessFromAzureServices_

**Comment by oxisto** [comment]
Fixed by #68.
