### ISSUE TITLE
Refactor Requirements Handling in the UI

### ISSUE THREAD

**Issue by immqu** [clouditor/clouditor#661]
- Discuss if the UpdateCloudService should use an Update method instead of Save (see https://github.com/clouditor/clouditor/blob/main/service/orchestrator/cloud_service.go#L133)
- When a new requirement is added in the UI (https://orchestrator-dev.k8s.medina.esilab.org/cloud), the NL2CNL Translator needs to be informed (see https://nl2cnl-translator-dev.k8s.medina.esilab.org/docs#/default/get_reo_for_tom_create_reo_for_requirement__tom_code__post) -> Done

**Comment by immqu** [comment]
This should be done with a hook in the backend: when a new requirement is added, in the MEDINA Orchestrator a call to the Translator should be made

**Comment by lebogg** [comment]
I think using `Save` is the better way. The difference is that `Save` will update the entire entry with all given fields, INCLUDING zero value fields. `Update` only updates the fields which the user have set (are non-zero). E.g. we have a ```employee{id=1;name:"Max", mail: "max@cl.io"}```.  
`Save`  `employee{id=1;name="Max", mail: ""}` will update this employee to: `employee{id=1;name="Max", mail: ""}`
In contrary, `Update` `employee{id=1;name="Max", mail: ""}` would result in `employee{id=1;name="Max", mail: "max@cl.io"}`  (nothing would happen)

**Comment by oxisto** [comment]
We are updating the complete list of requirements currently, so Update works.
