### ISSUE TITLE
Update Azure/go-autorest/autorest/azure/auth -> Azure/azure-sdk-for-go/sdk/azidentity

### ISSUE THREAD

**Issue by anatheka** [clouditor/clouditor#726]
The Authentication with the Azure SDK for Go  "github.com/Azure/go-autorest/autorest/azure/auth" is legacy [(link)](https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authorization) and must be updated to "github.com/Azure/azure-sdk-for-go/sdk/azidentity" [link](https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication).

**Comment by oxisto** [comment]
We should probably move to the new Azure SDK anyway: https://github.com/clouditor/clouditor/issues/633

**Comment by anatheka** [comment]
FIxed by PR #739
