### ISSUE TITLE
Rego: Utilize new Operators for Sets

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#741]
**Is your feature request related to a problem? Please describe.**
Currently, we implement the [isIn](https://github.com/clouditor/clouditor/blob/main/policies/operators.rego#L27-L36) function by ourselves.

**Describe the solution you'd like**
Meanwhile, there are [Built-In/Future-Built-In functions](https://www.openpolicyagent.org/docs/latest/policy-reference/#sets) doing that. Use them!

**Comment by anatheka** [comment]
Do we really need functionality for sets? I think we only have arrays. However, we can use the built-in keywords some, in and every.
