### ISSUE TITLE
pass []any as any in variadic function

### ISSUE THREAD

**Issue by alingse** [clouditor/clouditor#748]
**Describe the bug**

i am writing a [linter](https://github.com/alingse/asasalint) to lint that pass []any as any in variadic function

and run github Actions for some top go packages, this package failed

see github actions lint result here https://github.com/alingse/asasalint/runs/7271302223?check_suite_focus=true

**To Reproduce**

clouditor/persistence/gorm/gorm.go:210:36: pass []any as any to func Where func(query interface{}, args ...interface{}) (tx *gorm.io/gorm.DB)

```Go
// Update will update the record with non-zero fields. Note that to get the entire updated record you have to call Get
func (s *storage) Update(r any, query any, args ...any) error {
	return s.db.Model(r).Where(query, args).Updates(r).Error
}
```
and gorm Where signature

```Go
// Where add conditions
func (db *DB) Where(query interface{}, args ...interface{}) (tx *DB) {
	tx = db.getInstance()
	if conds := tx.Statement.BuildCondition(query, args...); len(conds) > 0 {
		tx.Statement.AddClause(clause.Where{Exprs: conds})
	}
	return
}
```

**Expected behavior**

```Go
// Update will update the record with non-zero fields. Note that to get the entire updated record you have to call Get
func (s *storage) Update(r any, query any, args ...any) error {
	return s.db.Model(r).Where(query, args...).Updates(r).Error
}
```

**Additional context**

other's `Where` use in https://github.com/clouditor/clouditor/blob/main/persistence/gorm/gorm.go

**Comment by oxisto** [comment]
This should be fixed in the meantime by #801
