### ISSUE TITLE
Creating API Key fails since ".clouditor" directory doesn't exist

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#786]
**Describe the bug**
```
INFO[0000] API key does not exist at the default location yet. We will create a new one  component=auth
ERRO[0000] Error while saving the new API key: error while opening the file: open /home/lebogg/.clouditor/api.key: no such file or directory  component=auth
```

**To Reproduce**
Start engine with non-existing folder ".clouditor" in home

**Expected behavior**
Clouditor creates folder in home when it not exist or in  "/root" in the case of root (e.g. using Docker)

**Comment by harkamals** [comment]
Workaround: `mkdir -p ~/.clouditor`
