### ISSUE TITLE
Discover tags from AWS

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#825]
**Is your feature request related to a problem? Please describe.**

We want to retrieve tags from the cloud resources and store them into our generalised cloud resource. It is already modelled in the ontology, but not yet filled in the discoverer.

**Comment by oxisto** [comment]
It seems already for k8s and Azure.

**Comment by anatheka** [comment]
> It seems already for k8s and Azure. Double-check if it is there for all resources.

For azure, all labels are set.

**Comment by oxisto** [comment]
> > It seems already for k8s and Azure. Double-check if it is there for all resources.
> 
> For azure, all labels are set.

Excellent. I have tried to add the labels/tags, where applicable in the #820 PR.
