### ISSUE TITLE
Add missing authorisation checks to all services

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#833]
```[tasklist]
- [ ] https://github.com/clouditor/clouditor/issues/1060
- [x] `ListEvidences` in Evidence Store service? (certification stuff, e.g. ListCertification)
- [ ] #1056
- [ ] https://github.com/clouditor/clouditor/issues/1058
- [ ] https://github.com/clouditor/clouditor/issues/1059
```

_Originally posted by @lebogg in https://github.com/clouditor/clouditor/pull/824#pullrequestreview-1156198326_

**Comment by anatheka** [comment]
Do we also need to check the following endpoints (and maybe some more) for an authorization strategy? I don't think weneed to check them against the Cloud Service ID, but an admin scope or something else. 
- Create/Update/RemoveCatalog
- Create/Update/RemoveMetric
- UpdateMetricImplementation
- Create/Update/RemoveCertificate

**Comment by oxisto** [comment]
> Do we also need to check the following endpoints (and maybe some more) for an authorization strategy? I don't think weneed to check them against the Cloud Service ID, but an admin scope or something else.
> 
> * Create/Update/RemoveCatalog
> * Create/Update/RemoveMetric
> * UpdateMetricImplementation
> * Create/Update/RemoveCertificate

Create/Update/RemoveCertificate has a cloud service ID. The rest I would keep as-is for now until we introduce more fine-grained permissions.

**Comment by lebogg** [comment]
And Create/Update/RemoveCertificate is/should be done in https://github.com/clouditor/clouditor/issues/1056 (see tasks above)
