### ISSUE TITLE
Enhance Catalog APIs

### ISSUE THREAD

**Issue by anatheka** [clouditor/clouditor#836]
We have to document and if necessary update the catalog APIs. 

Currently the API returns the following: 
- ListCatalogs -> List of catalogs with the corresponding categories
- GetCatalog -> Catalog with categories and corresponding controls
- ListControls -> List of controls with sub-controls (aka TOMs)
- GetControl -> Sub-control (aka TOM) with corresponding metrics

@anatheka would expect that ListCatalogs returns the whole catalog. Futhermore, for GetX and ListX I would expect the same objects (with the same depth) to be returned. Only once as a list of objects and once as a single object.

**Comment by lebogg** [comment]
"ListCatalogs returns the whole catalog" -> I think we decided to only get one or two levels at max. Otherwise, we would load the whole DB and thats not possible or better say, shouldn't be done this way

**Comment by oxisto** [comment]
> We have to document and if necessary update the catalog APIs.
> 
> Currently the API returns the following:
> 
> * ListCatalogs -> List of catalogs with the corresponding categories
> * GetCatalog -> Catalog with categories and corresponding controls
> * ListControls -> List of controls with sub-controls (aka TOMs)
> * GetCatalog -> Sub-control (aka TOM) with corresponding metrics
> 
> @anatheka would expect that ListCatalogs returns the whole catalog. Futhermore, for GetX and ListX I would expect the same objects (with the same depth) to be returned. Only once as a list of objects and once as a single object.

Retrieving a single item should return objects with a deeper depth than just a list. Because in a list, you might only interested in the names, the overall count, etc., but not the detail.

**Comment by oxisto** [comment]
We *could* think about additional query parameters that configure how much is returned. I think this is something that Azure does also.

**Comment by anatheka** [comment]
> We _could_ think about additional query parameters that configure how much is returned. I think this is something that Azure does also.

Azure changed that already. Maybe we should discuss this together sometime and not here in the comments. I think that is easier.
