### ISSUE TITLE
Provide a way to add manual evaluation results

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#838]
**Is your feature request related to a problem? Please describe.**

We need a way to add manual evaluation results for controls that we cannot monitor manually.

**Describe the solution you'd like**

API + Dashboard

**Comment by oxisto** [comment]
Probably less an API issue, more a dashboard + modelling issue. What should be included in the evidence value, etc.?

**Comment by anatheka** [comment]
TODO @oxisto: Move to UI project.
