### ISSUE TITLE
Check Update* and GetMetricConfiguration

### ISSUE THREAD

**Issue by anatheka** [clouditor/clouditor#844]
The following should be checked in an separate PR/Issue.

UpdateMetricConfiguration
- [x] isDefault is not updated, if not available in request -> set to false (Fixed in PR #1124 )
- [x] grpc does not returns the isDefault field (see comment in PR #1124 )
- [x] updatedAt is always set to 1970-01-01T00:00:00Z

GetMetricConfiguration: 
- [x] MetricId and cloudServiceId not available after initialization (curl call)

_Originally posted by @anatheka in https://github.com/clouditor/clouditor/issues/815#issuecomment-1297123745_

**Comment by lebogg** [comment]
Check again @anatheka

**Comment by anatheka** [comment]
If isDefault is missing in request, it is not available in the response, neither in the response from GetMetricConfiguration.
