### ISSUE TITLE
Query HTTP request is of type `post`

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#860]
https://github.com/clouditor/clouditor/blob/6a786ff7e9fbb670426bd8f84b91d829bca739ff/api/discovery/discovery.proto#L48-L53

Should be `get`, right?

**Comment by oxisto** [comment]
Can you send the contents of `QueryRequest` as query parameters? Then yes, this can be converted into a `GET`.

**Comment by lebogg** [comment]
Yes, there is no big difference to the `list` calls, e.g. `ListAssessmentResults`.

**Comment by anatheka** [comment]
Obsolete
