### ISSUE TITLE
Add policy operator 'IsIn'

### ISSUE THREAD

**Issue by anatheka** [clouditor/clouditor#909]
For some "customized" metrics an 'IsIn' operator is needed. 
Do we want to add that?

**Comment by lebogg** [comment]
1) In
https://github.com/clouditor/clouditor/blob/b4bd948096c95c4a94311969ee81aeaf84d7b532/api/assessment/metric.proto#L110

2) And add it to the the "compare" function, using it as a delegator function for all operators

**Comment by anatheka** [comment]
See also Issue #741
