### ISSUE TITLE
Make sure evidences and assessment results are not lost when the connection is broken

### ISSUE THREAD

**Issue by anatheka** [clouditor/clouditor#955]
We need to ensure that the evidences and assessment results are not lost when the connection is broken. We need to make sure that the evidences/assessment results must be both stored in the DB and sent to the following components as soon as the connection is re-established.

**Comment by oxisto** [comment]
In addition to that, we should get rid of the assessment results API in the assessment service, since this is not persisted and was just for debugging results that were not properly transmitted.

**Comment by oxisto** [comment]
This was fixed in https://github.com/clouditor/clouditor/pull/977
