### ISSUE TITLE
Add filtering for ListEvidences

### ISSUE THREAD

**Issue by anatheka** [clouditor/clouditor#967]
The following filter options should be added
- CloudServiceID
- ToolID
- ~~Resource~~ -> is done by #1021 in the future when we added resource message to proto (#1016)

**Comment by lebogg** [comment]
Regarding last item `resource`: @anatheka I guess you mean the resource id by that?
If so, then we should resolve #1016 ?

**Comment by anatheka** [comment]
I meant the resource identifier, e.g., "/azure/00000000-0000-0000-0000-000000000000/resourceGroups/*". But yes, we should update the evidence message with the newly introduced Resource before..
